# Khối chứa các cấu hình xử lý kết nối mạng
events {
  # Số lượng kết nối tối đa mà Nginx có thể xử lý cùng một lúc
    worker_connections 1024;
}

http {
    # MIME types: HTML, CSS, JS, hình ảnh
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Cấu hình Load Balancer cho Backend
    upstream backend_servers {
        server backend1:8080;
        server backend2:8080;
    }

    server {
        listen 80;

        # 1. Tất cả API bắt đầu bằng /api/ đẩy sang Backend Load Balancer
        location /api/ {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 2. Redirect short URL (ví dụ: http://localhost/q0U8aX) đẩy sang Backend
        location ~ ^/[a-zA-Z0-9]{6,8}$ {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 3. Tất cả request giao diện còn lại route tới Nuxt Frontend
        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}