spring:
  application:
    name: url-shortener
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/url_shortener_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres_user}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8080}
